### PR TITLE
hide deprecation notice when subclassing ember bootstrap classes

### LINKED ISSUE #24: Deprecation notice in ember-bootstrap 4
Extending BsForm is deprecated in ember-bootstrap 4. How would this addon need to change to keep working?

`Extending from ember-bootstrap component classes is not supported, and might break anytime. Detected subclassing of <BsForm> component.`
```
2VM5842:94 Ember Inspector (Deprecation Trace): Extending from ember-bootstrap component classes is not supported, and might break anytime. Detected subclassing of <BsForm> component.

        at HANDLERS.<computed> (https://localhost:4201/assets/vendor.js:43285:9)
        at invoke (https://localhost:4201/assets/vendor.js:43297:9)
        at Object.deprecate (https://localhost:4201/assets/vendor.js:43253:28)
        at Class.target.init (https://localhost:4201/assets/vendor.js:171258:94)
        at initialize (https://localhost:4201/assets/vendor.js:35968:9)
        at Function.create (https://localhost:4201/assets/vendor.js:36517:9)
        at Function.superWrapper (https://localhost:4201/assets/vendor.js:37641:22)
        at Function.create (https://localhost:4201/assets/vendor.js:108845:29)
        at Function.superWrapper [as create] (https://localhost:4201/assets/vendor.js:37641:22)
```

### PR DESCRIPTION
**Pull request by basz**
fixes #24 

should this also be done for https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/addon/components/bs-form/element.js

### CODE REVIEW

**Comment by basz** [comment]
travis fails. with 'yarn install --no-lockfile --non-interactive' but runs fine with 'yarn install'.

dunno... seems to come from https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/tests/integration/components/bs-form-element-test.js#L119

**Comment by jelhan** [comment]
Thanks for working on this one!

> should this also be done for https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/addon/components/bs-form/element.js

Yes.

> travis fails. with 'yarn install --no-lockfile --non-interactive' but runs fine with 'yarn install'.

Do you see the same for current `master` or only for this feature branch? If the issue is also on current `master` it seems to be caused by a new version of some dependency. We would need to track it down to a specific dependency.

**Comment by basz** [comment]
On holidays atm... feel free to ping me in ~1.5 weeks

**Comment by jelhan** [comment]
> travis fails. with 'yarn install --no-lockfile --non-interactive' but runs fine with 'yarn install'.

See #26. Should be fixed by #27.

**Comment by basz** [comment]
ok element class also done

**Comment by jelhan** [comment]
Thanks for the great work! Merged as the failing tests are not related.

**Pull request merged**
