### PR TITLE
use get for nested properties

### PR DESCRIPTION
**Pull request by basz**
attempt to address https://github.com/kaliber5/ember-bootstrap-changeset-validations/pull/27#issuecomment-661064618

### CODE REVIEW

**Comment by jelhan** [comment]
Does this fixes the issue for you? Can you add a test that is failing without but passing with these change?

**Comment by basz** [comment]
No unfortunately not. A console.log shows it can get the correct error messages now, but the ui does not reflect an validation error.

**Comment by jelhan** [comment]
Do you have time to add a failing test? That would help a lot with debugging.

**Comment by basz** [comment]
By further investigation, that fix does seem to remove my issue... So think it can be merged as is.

**Comment by jelhan** [comment]
Can you please add a test, which is failing before but passing with this test? This will help us to prevent regressions.

**Comment by basz** [comment]
will this be sufficient?

**Comment by jelhan** [comment]
Looks good to me. Thanks a lot!

**Pull request merged**
